name: esnaf_kurye
description: Esnaf-Kurye Lojistik Köprüsü MVP

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Navigasyon & State
  go_router: ^13.0.0
  provider: ^6.1.1

  # Harita
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Ağ
  http: ^1.2.0
  socket_io_client: ^2.0.3+1

  # Depolama
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Yardımcılar
  intl: ^0.19.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
